from flask import Flask, render_template_string
from hubspot_client import get_all_deals, get_pipeline_stages
from analyzer import analyze_pipeline

app = Flask(__name__)

HTML_WRAPPER = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pipeline Intelligence Report</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 960px; margin: 0 auto; padding: 2rem; background: #f9f9f9; color: #1a1a1a; }
        h1 { font-size: 1.8rem; border-bottom: 2px solid #01696f; padding-bottom: 0.5rem; color: #01696f; }
        h2 { font-size: 1.3rem; margin-top: 2rem; color: #222; }
        table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
        th { background: #01696f; color: white; padding: 0.6rem 1rem; text-align: left; }
        td { padding: 0.6rem 1rem; border-bottom: 1px solid #ddd; }
        tr:nth-child(even) { background: #f3f3f3; }
        .report { background: white; padding: 2rem; border-radius: 8px; box-shadow: 0 2px 12px rgba(0,0,0,0.07); }
        .meta { color: #666; font-size: 0.9rem; margin-bottom: 1.5rem; }
    </style>
</head>
<body>
    <div class="report">
        <h1>🧠 Pipeline Intelligence Report</h1>
        <p class="meta">Generated by Pipeline Intelligence Agent · Powered by GPT-4o + HubSpot</p>
        {{ report_html | safe }}
    </div>
</body>
</html>
"""

@app.route("/")
def index():
    deals = get_all_deals()
    stages = get_pipeline_stages()
    report_html = analyze_pipeline(deals, stages)
    return render_template_string(HTML_WRAPPER, report_html=report_html)

@app.route("/health")
def health():
    return {"status": "ok", "agent": "pipeline-intelligence-agent"}, 200

if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=8080)